// This file is automatically generated. Do not edit it directly.
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL =
	process.env.NEXT_PUBLIC_SUPABASE_URL ??
	process.env.VITE_SUPABASE_URL ??
	'';

const SUPABASE_PUBLISHABLE_KEY =
	process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY ??
	process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY ??
	process.env.VITE_SUPABASE_PUBLISHABLE_KEY ??
	'';

// Create a lazy-initialized client to avoid errors during Next.js static build
let _supabase: SupabaseClient<Database> | null = null;

function getSupabaseClient(): SupabaseClient<Database> {
	if (_supabase) return _supabase;
	
	if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
		throw new Error(
			'Supabase env vars missing. Set NEXT_PUBLIC_SUPABASE_URL and NEXT_PUBLIC_SUPABASE_ANON_KEY (or NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY).'
		);
	}
	
	_supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
	return _supabase;
}

// Export a proxy that creates the client on first access (browser only)
export const supabase = typeof window !== 'undefined' 
	? getSupabaseClient()
	: new Proxy({} as SupabaseClient<Database>, {
		get(_, prop) {
			// During SSR/build, return no-op functions for common methods
			if (prop === 'auth') {
				return new Proxy({}, {
					get() {
						return () => Promise.resolve({ data: null, error: null });
					}
				});
			}
			if (prop === 'from') {
				return () => ({
					select: () => ({ data: null, error: null }),
					insert: () => Promise.resolve({ data: null, error: null }),
					update: () => Promise.resolve({ data: null, error: null }),
					delete: () => Promise.resolve({ data: null, error: null }),
				});
			}
			return () => Promise.resolve({ data: null, error: null });
		}
	});
